Added main function
suisseWalter/factorio-benchmark pull request #17
Opened 2023-01-10 21:04 UTC by flameSla

2023-01-11 15:32 UTC, rpdelaney requested changes

2023-01-11 15:32 UTC, rpdelaney commented on benchmarker.py
> +    print(f"Map benchmarked at {ups} UPS\r\n")
```suggestion
    print(f"Map benchmarked at {ups} UPS")
    print("")
```

2023-01-11 15:32 UTC, rpdelaney commented on benchmarker.py
> +    print("==================\r\n")
```suggestion
    print("==================")
    print("")
```

2023-01-11 15:32 UTC, rpdelaney commented on benchmarker.py
> +    if folder is None:
```suggestion
    if not Folder:
```

2023-01-11 15:32 UTC, rpdelaney commented on benchmarker.py
> +    if filenames is None:
```suggestion
    if not filenames:
```

2023-01-11 15:59 UTC, suisseWalter commented on benchmarker.py
> +    print("\r\nthe benchmark is finished")
not sure if 


> ==================
> creating graphs
> saving benchmark results
> 
> the benchmark is finished

is the best wording, because once the last message comes the actual benchmarks have long finished. maybe replace the last message with, `data processed succesfully` and add a `benchmarks finsished, processing data` before `creating graphs`(or replace that)

2023-01-11 17:09 UTC, rpdelaney commented on benchmarker.py
> +    print(f"Map benchmarked at {ups} UPS\r\n")
The changes I requested around `\r\n` are why I am blocking this PR, since we should be agnostic about line-endings in what we print to stdout as much as possible.

2023-01-11 20:28 UTC, flameSla commented on benchmarker.py
> +    if factorio_bin is None:
I'm not sure it's better this way
I mean that the programmer who calls knows better what to pass to him in the parameter
for example: for the "folder" parameter, I may want to pass ""

2023-01-11 20:39 UTC, flameSla commented on benchmarker.py
> +    print("\r\nthe benchmark is finished")
data processing and plotting happens instantly, all these messages appear simultaneously
I added this for a better understanding at what stage the error occurred

I would leave it like that, but change it as you like, it doesn't matter to me

2023-01-12 14:37 UTC, rpdelaney commented on benchmarker.py
> +    if factorio_bin is None:
It's not a hill I'll die on. (I think we should replace these strings with `pathlib.Path`s eventually anyway :) )

2023-01-12 14:37 UTC, rpdelaney approved these changes

2023-01-12 15:21 UTC, suisseWalter approved these changes
Codewise it looks all good. 
Therefore it can be merged(please sqash on merge, and edit the squash message to be reasonable)

One thing to note is: please describe the contents of your pr/commit a bit better. Try to give a reason for your change aswell as describe it.( I myself also don't do it all the time and should improve that in the future)

2023-01-12 15:40 UTC, merged