Feature/migration
suisseWalter/factorio-benchmark pull request #32
Opened 2023-01-15 10:31 UTC by suisseWalter

automatic save file migration option.

2023-01-15 17:00 UTC, flameSla commented on benchmarker.py
>      if args.disable_mods:
imho it is better to leave the call to the **create_mods_dir()** function
it will be required on Windows
and on Linux after manually installing Factorio

2023-01-15 17:07 UTC, flameSla commented
factorio_rcon -> requirements.txt

2023-01-15 17:13 UTC, flameSla commented on benchmarker.py
> +            os.path.splitext(map)[0] + get_factorio_version(factorio_bin).replace(".", "") + ".zip"
```suggestion
            os.path.splitext(map)[0] + "_" + get_factorio_version(factorio_bin).replace(".", "_") + ".zip"
```
imho so the version will be clearer

2023-01-15 17:16 UTC, suisseWalter commented on benchmarker.py
> +            os.path.splitext(map)[0] + get_factorio_version(factorio_bin).replace(".", "") + ".zip"
but longer. yes it's more readable, but the filenames are already really long most of the time. and so adding even more (especially with multiple migrations) isn't optimal.

2023-01-15 18:00 UTC, flameSla commented
how do I migrate from version 0.16?

2023-01-15 18:12 UTC, suisseWalter commented
replace the link with the proper version for windows. (probably full/win)
also you might have to remove the factorio folder before running `-u`. 
```
benchmarker -u --version_link https://www.factorio.com/get-download/1.0.0/headless/linux64 
benchmarker -mi
benchmarker -u
bemchmarker -mi 
```

2023-01-17 14:54 UTC, rpdelaney requested changes
We should never have `os.path` operations inside a `pathlib.Path`.. the latter can do everything with its built-in methods.

2023-01-17 15:29 UTC, rpdelaney commented on benchmarker.py
> +    print("migrating map:" + map)
```suggestion
    print(f"migrating map: {map}")
```
nit

2023-01-17 15:33 UTC, rpdelaney commented on benchmarker.py
> +    lastlines = ["", "", "", "", "", "", "", ""]
Suggestion: you might like `collections.deque`

2023-01-22 22:16 UTC, rpdelaney commented on benchmarker.py
> +def sync_mods(map: PurePath, disable_all: bool = False) -> None:
Yay!

2023-01-22 22:21 UTC, rpdelaney commented on benchmarker.py
> +        set_mod_command = str(PurePath("fmm", fmm_name)) + " --game-dir factorio disable"
```suggestion
        set_mod_command = f"{PurePath('fmm', fmm_name)} --game-dir factorio disable"
```

2023-01-22 22:23 UTC, rpdelaney commented on benchmarker.py
> +        factorio_bin if factorio_bin else PurePath("factorio", "bin", "x64", "factorio")
```suggestion
        factorio_bin or PurePath("factorio", "bin", "x64", "factorio")
```

2023-01-22 22:25 UTC, rpdelaney commented on benchmarker.py
> +        sync_mods(map=PurePath(""), disable_all=True)
```suggestion
        sync_mods(map=PurePath(), disable_all=True)
```
smallest nit ever

2023-01-22 22:25 UTC, rpdelaney approved these changes
Good for me :)

2023-01-24 20:45 UTC, merged